### ISSUE TITLE
希望作者能够抽时间继续更新谢谢

### ISSUE THREAD

**Issue by Yu1993Yu** [sublime-china/sublime-merge-tutorials#2]
相对来说sublime merge是比较新的git客户端工具，之前使用sublime进行git管理都是通过sublime text的git插件。
现在sublime直接推出了这样一款软件，网上的中文教程很少，针对小白git用户，作者的叙述方式与逻辑非常清晰，希望能够持续更新此教程，帮助更多的newer~

**Comment by floydawong** [comment]
感谢支持, 我会努力更新的~
