### ISSUE TITLE
不知道作者有没有办法解决git客户端都会遇到中文乱码的问题？

### ISSUE THREAD

**Issue by Yu1993Yu** [sublime-china/sublime-merge-tutorials#3]
在sublime text 中可以用插件converttoUTF8插件转成GB2312编码格式解决中文乱码的问题。
但是在sublime merge中没办法直接导入converttoUTF8插件（如果直接复制到packages目录，会出现converttoUTF8插件，但是为灰色，无法使用）。
在Fork中也出现中文乱码，没有找到编码或者语言设置选项

目前只在博文中看到sourcetree有中文语言选项设置，因为使用sourcetree必须联网注册account，条件限制没办法使用。（不知道有没有办法绕过这个操作）

不知道作者有没有相关推荐办法解决这个问题？谢谢

**Comment by maboloshi** [comment]
最好的办法 直接批量用工具将全部源代码转成UTF8编码格式的

**Comment by floydawong** [comment]
只能建议用UTF8了， 如果不是这个编码， 像楼上说的， 用其他工具转一下咯~

**Comment by Yu1993Yu** [comment]
> 最好的办法 直接批量用工具将全部源代码转成UTF8编码格式的

这确实是一个根本的解决办法，只不过正是因为太根本了，所以公司的项目里没办法去实现，牵涉的东西太多了。
已经实践了两个解决办法：
1. sourcetree里面可以设置编码格式，改为GB2312，修改代码显示部分包含中文注释显示正常。但是在更新图谱中如果有中文的commit注释，则会变成乱码(因为这里的中文应该是UTF-8编码)。

2. 如果使用vscode结合git插件，可以较好的解决这个问题，因为vscode里面可以设置编码格式，插件里面也可以单独设置编码格式，所以两个地方的中文(蛋疼的两个编码格式的中文)，都会显示正常

**Comment by Yu1993Yu** [comment]
> 只能建议用UTF8了， 如果不是这个编码， 像楼上说的， 用其他工具转一下咯~

同上，就是因为牵涉的东西太多，项目里很多回显是写死了，怕改了编码格式就都乱了。。。所以只能选择折中的办法，虽然也是一个小问题，毕竟你在git客户端里面只是预览下代码，需要比较的话可以直接调用第三方软件，但是强迫症还是有点不爽。。。。

**Comment by Yu1993Yu** [comment]
sourcetree可以基本上解决这个问题了，因为sourcetree是难得的有编码格式设置选项的客户端。
整体上来说，有两部分会因为编码格式不同而产生冲突(**在确定没有办法更改源代码编码格式，只能是GB2312的情况下**)：
1. git客户端会显示的log日志，也就是分支图旁边的commit注释，比如`某某在什么时候提交了什么，对什么做了修改`这一部分包含的中文内容。git默认的编码格式是UTF-8，所以如果在sourcetree的选项里面把编码格式设置为GB2312，则这一部分会出现乱码（其实强烈建议commit注释应该全英文化，陈旧的国企......）。但是因为没有办法改变源代码的编码格式，所以，只有把sourcetree里面的编码选项改为GB2312。
2. 为了解决以上的问题，需要设置git的log日志输出编码格式从默认的UTF-8改为GB2312。方法是修改`.gitconfig`文件，添加`[i18n]`选项，在下面添加`logoutencoding = gb2312`字段。另外，为了和remote的编码格式统一，继续在下面添加`commitencoding = gb2312`字段。
3. 保存，重新启动sourcetree，log日志的输出因为改为了gb2312，所以在sourcetree里面也会正常显示了。如果还是乱码，有可能需要重新刷一下log日志，提交一个什么东西，让log日志以新的编码格式保存。

以上便是不得已而为之的办法。
